name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Welcome"
        run: echo "Welcome to this gihub action"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye Job"
        run: echo "Bye bye github action" 

      # - name: failed jobs
      #   run: exit 1

    

        